pipeline:

  docker:
    image: plugins/docker
    repo: chrisns/monocole
    tags:
      - latest
      - ${DRONE_BUILD_NUMBER}
    secrets: [ docker_username, docker_password ]

  deploy:
    image: docker
    secrets: [ TOKEN ]
    commands:
      - docker deploy --compose-file docker-compose.yml monocole
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    when:
      branch: master