version: "3"
services:
  gateway:
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.40'
          memory: 128M
      restart_policy:
        condition: any
        delay: 5s
    image: chrisns/monocole:${DRONE_BUILD_NUMBER}
    environment:
      - TOKEN=${TOKEN}